### ISSUE TITLE
Distribution for simulating communities

### ISSUE THREAD

**Issue by Dylan1021** [nick-youngblut/MGSIM#3]
Hi, I am trying to use uniform distribution to generate the communities with low = 6 and high = 8 so that I can get values around 7 and I use the following command:
`MGSIM communities --abund-dist=uniform --abund-dist-p=low:6,high:8 --n-comm=30`
But the abundance file is like this:
`Community	Taxon	Perc_rel_abund	Rank`
`1	GCF_000016065.1_genomic	0.367704312	1`
`1	GCF_000187745.1_genomic	0.344591406	2`
`...`
where the value of `perc_rel_abund` is not around 7, could you please help me with this problem?
Many thanks :)

**Comment by nick-youngblut** [comment]
@Dylan1021 the abundance distribution is normalized, so you will never get counts between 6 and 8; you will just get the normalized (fractional) counts.

**Comment by Dylan1021** [comment]
@nick-youngblut I see, thank you for your help. :)
