### ISSUE TITLE
Failed to simulate long reads

### ISSUE THREAD

**Issue by Dylan1021** [nick-youngblut/MGSIM#4]
Hi,

I am trying to use MGSIM to simulate Pacbio sequencing data, however, the command parameter `--pb-seq-depth` doesn't work as I still get the illumina results. Here is the command I used:

```
MGSIM reads --pb-seq-depth 1e7 --tmp-dir ./temp_reads --rndSeed 8294 -n 256 --gzip ./genome_list.tsv ./communities/comm_wAbund.txt ./reads
```
and console output is:
```
24-01-04 14:17:20,910 - Reading genome table: ./genome_list.tsv 
2024-01-04 14:17:21,067 -   Getting genome sizes (no. of threads: 256) 
2024-01-04 14:17:43,757 - Reading abundance table: ./communities/comm_wAbund.txt 
2024-01-04 14:17:43,958 - Creating sample-taxon list... 
2024-01-04 14:17:44,761 - Simulating illumina reads... 
2024-01-04 14:17:44,825 - Simulating Illumina reads... 
```
ps: the real file path has been hidden for privacy ~

Could you please help me with this? Many thanks!

**Comment by nick-youngblut** [comment]
I should change the UI, since it is confusing.

You have to use `--sr-seq-depth 0`; otherwise, Illumina reads will still be simulated. See https://github.com/nick-youngblut/MGSIM/blob/master/MGSIM/Commands/Reads.py

**Comment by nick-youngblut** [comment]
I've added a simple [tutorial](https://github.com/nick-youngblut/MGSIM?tab=readme-ov-file#tutorial) to clarify, and I set `--sr-seq-depth 0` as default. 
Let me know if you have any more issues.

**Comment by Dylan1021** [comment]
Many thanks for your great help!
